spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xuanke_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      pool-name: hikariCP
      minimum-idle: 20
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      connect-timeout: 5000ms
      timeout: 5000ms
      client-type: lettuce
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0

jwt:
  signKey: xuanke_jwt_debug_signKey