spring:
  profiles:
    active: dev
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/xuanke_db.sql
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      enabled: false
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

mq:
  env: local
  basic:
    info:
      queue:
        name: ${mq.env}.middleware.mq.basic.info.queue.xuanke
      exchange:
        name: ${mq.env}.middleware.mq.basic.info.exchange.xuanke
      routing:
        key:
          name: ${mq.env}.middleware.mq.basic.info.routing.key.xuanke

server:
  error:
    whitelabel:
      enabled: false
  port: 10086

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler